name: Terraform

on:
  pull_request:
    branches:
      - main
    paths:
      - "infra/**"
  push:
    branches:
      - main
    paths:
      - "infra/**"
  workflow_dispatch:

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_SECRET }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.13.5

      - name: Install Task
        uses: go-task/setup-task@v1

      - name: Terraform Init
        run: task terraform:ci:init

      - name: Terraform Plan
        run: task terraform:ci:plan

      - name: Upload Plan to Summary
        working-directory: infra
        run: |
          {
            echo "## Terraform Plan"
            echo ""
            echo "\`\`\`terraform"
            cat plan.txt
            echo "\`\`\`"
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v7
        with:
          name: tfplan
          path: infra/tfplan
          retention-days: 1

  deploy:
    name: Terraform Deploy
    runs-on: ubuntu-latest
    needs: plan
    if: github.event_name == 'push' && github.ref_name == 'main'
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_SECRET }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.13.5

      - name: Install Task
        uses: go-task/setup-task@v1

      - name: Download Terraform Plan
        uses: actions/download-artifact@v8
        with:
          name: tfplan
          path: infra/

      - name: Terraform Init
        run: task terraform:ci:init

      - name: Run Terraform Deploy
        run: task terraform:ci:deploy
